---
- name: Install MicroK8s and run a pod
  hosts: demo
  become: true

  tasks:
    - name: Install MicroK8s
      shell: snap install microk8s --classic

    - name: Add current user to MicroK8s group
      shell: usermod -a -G microk8s $USER
      environment:
        USER: "{{ ansible_user }}"

    - name: Enable MicroK8s add-ons
      shell: microk8s enable dns dashboard storage

    - name: Wait for MicroK8s to start
      shell: microk8s status --wait-ready

    - name: Deploy sample pod
      shell: microk8s kubectl run nginx1 --image nginx --restart=Never
